### ISSUE TITLE
bash: /home/rosdev/ros2_ws/install/setup.bash: No such file or directory

### ISSUE THREAD

**Issue by justin-ren** [BrunoB81HK/ros2-workspace-devcontainer-template#6]
hit below error after opened terminal:
> bash: /home/rosdev/ros2_ws/install/setup.bash: No such file or directory

can't find this script:
``` bash
rosdev@mint21:~/ros2_ws$ pwd
/home/rosdev/ros2_ws
rosdev@mint21:~/ros2_ws$ ls
src
```

**Comment by BrunoB81HK** [comment]
This is normal since you haven't build your workspace yet. You can ignore it.

This is due to the fact that the `~/.bashrc` file contains both `source '/opt/ros/$ROS_DISTRO/setup.bash'` and `source '~/ros2_ws/install/setup.bash'`.

**Comment by schroettinger** [comment]
Following replacement at the Dockerfile converts the bash error to an own warning. Remove the else part to get totally rid of a comment when opening a bash.


> RUN echo 'source /opt/ros/'$ROS_DISTRO'/setup.bash' >> /home/$USERNAME/.bashrc \
>     && echo 'source /home/'$USERNAME'/ros2_ws/install/setup.bash' >> /home/$USERNAME/.bashrc

```Dockerfile
# Setup bashrc
## Make ros2 public to the system via `source` command
RUN echo "source /opt/ros/$ROS_DISTRO/setup.bash" >> /home/$USERNAME/.bashrc

## Check if own build has been made; if yes, source it 
RUN echo "if [ -f \"/home/$USERNAME/ros2_ws/install/setup.bash\" ]; then" >> /home/$USERNAME/.bashrc \
    && echo "    source /home/$USERNAME/ros2_ws/install/setup.bash" >> /home/$USERNAME/.bashrc \
    && echo "else" >> /home/$USERNAME/.bashrc \
    && echo "    echo \"/home/$USERNAME/ros2_ws/install/setup.bash has not yet been created.\"" >> /home/$USERNAME/.bashrc \
    && echo "    echo \"Make sure to build your package(s).\"" >> /home/$USERNAME/.bashrc \
    && echo "fi" >> /home/$USERNAME/.bashrc
    
```
(Unfotunatelly the previous `cat` solution at the RUN statement had docker build issues.)

**Comment by BrunoB81HK** [comment]
That is very cool! I think it is good to keep the warning. @schroettinge, can you provide those changes via a pull request?

**Comment by schroettinger** [comment]
sure, have a look at #7 :)

**Comment by BrunoB81HK** [comment]
Thanks a lot again @schroettinger for your contribution! 🎉
